FROM debian:bullseye-slim

# Add mipsel support and install build tools
RUN apt-get update && \
	apt-get -y install \
	build-essential \
	curl \
	g++-mipsel-linux-gnu \
	git \
	bc \
	bison \
	flex \
	cpio \
	jq && \
	rm -rf /var/lib/apt/lists/*

ENV CROSSCOMPILE="mipsel-linux-gnu-"
