name: Build docker build environments

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:

    runs-on: ubuntu-24.04

    strategy:
        matrix:
          tag: [mips, mipsel, mtk, octeon]
          type: [kernel, tools]
          exclude:
            - tag: mips
              type: kernel
            - tag: mtk
              type: tools
            - tag: octeon
              type: tools
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/ubnt-build:${{ matrix.tag }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check if image exists
        id: check
        run: |
          IMAGE_LOWER="$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"
          if docker manifest inspect "$IMAGE_LOWER" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Image $IMAGE_LOWER already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Image $IMAGE_LOWER does not exist, will build"
          fi

      - name: Build kernel environment
        if: ${{ matrix.type == 'kernel' && steps.check.outputs.exists == 'false' }}
        run: docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" -f ci/DOCKERFILE-${{ matrix.tag }} .

      - name: Build tools environment
        if: ${{ matrix.type == 'tools' && steps.check.outputs.exists == 'false' }}
        env:
          ARCH: ${{ matrix.tag }}
          TARGET: ${{ matrix.tag }}-linux-musl
        run: docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" --build-arg ARCH=${{ matrix.tag }} -f ci/DOCKERFILE-tools .

      - name: Push image to GitHub Container Registry
        if: ${{ steps.check.outputs.exists == 'false' }}
        run: docker push "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"
